name: Daily Job Scraper
on:
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 09:30 UTC = 16:00 MMT (Myanmar Time)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Yangon"
      JOBNET_EMAIL: ${{ secrets.JOBNET_EMAIL }}
      JOBNET_PASSWORD: ${{ secrets.JOBNET_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Daily Job Scraper
      run: |
        python daily_scraper.py
