name: Daily Job Scraper

on:
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 09:30 UTC = 16:00 MMT (Myanmar Time)
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Allows the workflow to push changes to the repository

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Yangon"
      JOBNET_EMAIL: ${{ secrets.JOBNET_EMAIL }}
      JOBNET_PASSWORD: ${{ secrets.JOBNET_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Daily Job Scraper
      run: |
        python daily_scraper.py

    - name: Upload logs artifact
      uses: actions/upload-artifact@v4
      with:
        name: etl-logs
        path: logs/

  process_logs:
    needs: scrape_jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download ETL logs artifact
      uses: actions/download-artifact@v4
      with:
        name: etl-logs
        path: artifacts

    - name: Organize logs into extract and transform directories
      run: |
        mkdir -p logs/extract logs/transform
        # Copy extract logs
        find artifacts/logs/extract -name "*.log" -exec cp {} logs/extract/ \; || echo "No extract logs found"
        # Copy transform logs
        find artifacts/logs/transform -name "*.log" -exec cp {} logs/transform/ \; || echo "No transform logs found"

    - name: Commit and push logs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add logs/
        git diff --cached --quiet || (git commit -m "Update ETL logs" && git push)
