name: Job Scraper

on:
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JOBNET_EMAIL: ${{ secrets.JOBNET_EMAIL }}
      JOBNET_PASSWORD: ${{ secrets.JOBNET_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: |
          python3 main.py

      - name: Commit and push changes in log file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jobnetmm_e_logs.log
          git commit -m "Update log file" || echo "No changes to commit"
          git push