name: Job Tracker

on:
  push:
    branches:
      - jobnetmm
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-and-log:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [jobnetmm, jobsdbsg, jobsdbth, jobstreetmalay, founditsg]

    env:
      TZ: "Asia/Yangon"
      JOBNET_EMAIL: ${{ secrets.JOBNET_EMAIL }}
      JOBNET_PASSWORD: ${{ secrets.JOBNET_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL for ${{ matrix.source }} and log
        run: |
          mkdir -p logs
          echo "Starting ETL for ${{ matrix.source }} ..." | tee logs/${{ matrix.source }}.log
          python main.py --source ${{ matrix.source }} >> logs/${{ matrix.source }}.log 2>&1

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.source }}
          path: logs/${{ matrix.source }}.log
          retention-days: 1

  commit-logs:
    name: Commit logs to repo
    runs-on: ubuntu-latest
    needs: extract-and-log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all logs
        uses: actions/download-artifact@v4
        with:
          path: logs-artifacts

      - name: Move all logs to logs/ dir
        run: |
          find logs-artifacts -name "*.log" -exec mv {} logs/ \;

      - name: Commit and push logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add logs/*.log
          git commit -m "Update ETL logs" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
